sonar.projectKey=we-livesystem_prj-we-livesystem-chat-service_e0a63449-c92a-4697-9dad-6ca6c7cdc0cb

#sonar.sourceEncoding=UTF-8
# sonar.javascript.lcov.reportPaths=./test/coverage/lcov.info
sonar.sources=./src
# sonar.tests=./test

# Include specific file types
sonar.inclusions=src/**/*.js,src/**/*.jsx,src/**/*.ts,src/**/*.tsx

# Coverage configuration
# sonar.coverage.exclusions=test/**/*,**/*.test.js,**/*.spec.js,**/*.test.ts,**/*.spec.ts,**/*.swagger.ts,**/*.dto.ts,**/*.constants.ts,**/*.interfaces.ts 

# Exclude test files from coverage analysis
sonar.exclusions=test/**/*,**/*.test.js,**/*.spec.js,**/*.test.ts,**/*.spec.ts,**/*.swagger.ts,**/*.dto.ts