export enum TableName {
    IAM_USERS = 'iam_users',
    USERS = 'users',
    TEMP_USERS = 'temp_users',
    PERFORMERS = 'performers',
    ADMINISTRATORS = 'administrators',
    TOKENS = 'tokens',
    DEVICES = 'devices',
    USER_GALLERIES = 'user_galleries',
    USER_PERFORMER_INTERACTIONS = 'user_performer_interactions',
    INTERACTION_POINT_TRANSACTIONS = 'interaction_point_transactions',
    USER_PERFORMER_BLOCKINGS = 'user_performer_blockings',
    USER_PERFORMER_LIKES = 'user_performer_likes',
    USER_PERFORMER_MEMOS = 'user_performer_memos',
    USER_PERFORMER_VIOLATION_REPORTS = 'user_performer_violation_reports',
    USER_CREDIT_CARDS = 'user_credit_cards',
    USER_POINT_PURCHASE_LOGS = 'user_point_purchase_logs',
    POINT_TRANSACTIONS = 'point_transactions',
    PERFORMER_MESSAGE_TEMPLATES = 'performer_message_templates',
    PERFORMER_GALLERIES = 'performer_galleries',
    PERFORMER_MONEY_REQUESTS = 'performer_money_requests',
    PERFORMER_SEARCH_KEYWORDS = 'performer_search_keywords',
    POINT_SUBSCRIPTIONS = 'point_subscriptions',
    SETTING_ACQUIRED_POINT_ACTIVATIONS = 'setting_acquired_point_activations',
    SETTING_ACQUIRED_POINTS = 'setting_acquired_points',
    SCHEDULED_NOTIFICATIONS = 'scheduled_notifications',
    SETTING_RECEIVED_NOTIFICATIONS = 'setting_received_notifications',
    SETTING_POINT_PRICES = 'setting_point_prices',
    SCHEDULED_NOTIFICATION_DETAILS = 'scheduled_notification_details',
    FILES = 'files',
    POINT_LOGS = 'point_logs',
    PERFORMER_SEARCH_TREND_WORDS = 'performer_search_trend_words',
    CAMPAIGN_BONUS_POINT_LOGS = 'campaign_bonus_point_logs',
    ADMIN_ADJUST_POINT_LOGS = 'admin_adjust_point_logs',
    ADMIN_NOTIFICATIONS = 'admin_notifications',
    PREFECTURES = 'prefectures',
    SETTING_BANNERS = 'setting_banners',
    GENERAL_SETTINGS = 'general_settings',
    POINT_SUBSCRIPTION_ACTIVATIONS = 'point_subscription_activations',
    CAMPAIGNS = 'campaigns',
    SETTING_INTERACTION_ITEM_PRICES = 'setting_interaction_item_prices',
    SETTING_REFERRAL_POLICIES = 'setting_referral_policies',
    REFERRAL_POINT_LOGS = 'referral_point_logs',
    APP_VERSIONS = 'app_versions',
    APP_INSTANCES = 'app_instances',
    AUDIT_FIELDS = 'audit_fields',
    USER_POINT_PRE_PURCHASE_LOGS = 'user_point_pre_purchase_logs',
    ACCOUNT_POINT_TRANSACTIONS = 'account_point_transactions',
    CONSUME_POINT_LOGS = 'consume_point_logs',
    ADMIN_NOTIFICATIONS_READ_STATUSES = 'admin_notifications_read_statuses',
    USER_WITHDRAW_LOGS = 'user_withdraw_logs',
    USER_SEND_LIVE_ITEM_LOGS = 'user_send_live_item_logs',
    CONTENT_APPROVALS = 'content_approvals',
    POSTS = 'posts',
    POST_FILES = 'post_files',
    POST_LIKES = 'post_likes',
    POST_COMMENTS = 'post_comments',
    POST_PAYMENT_LOGS = 'post_payment_logs',
    TENCENT_CALL_LIVES = 'tencent_call_lives',
    TENCENT_CALL_LIVE_PARTICIPANTS = 'tencent_call_live_participants',
    TENCENT_LIVE_STAGES = 'tencent_live_stages',
    PERFORMER_USER_FIRST_INTERACTION_LOGS = 'performer_user_first_interaction_logs',
    PERFORMER_STATISTICS_DAILY_LOGS = 'performer_statistics_daily_logs',
    USER_STATISTICS_DAILY_LOGS = 'user_statistics_daily_logs',
    PERFORMER_STATISTICS_MONTHLY_LOGS = 'performer_statistics_monthly_logs',
    USER_POINT_PURCHASE_REFUNDS = 'user_point_purchase_refunds',
    USER_GALLERY_GROUPS = 'user_gallery_groups',
    PERFORMER_GALLERY_GROUPS = 'performer_gallery_groups',
    PERFORMER_REWARDS_MESSAGE_DAILY_LOGS = 'performer_rewards_message_daily_logs',
    PERFORMER_EKCY_IMAGES = 'performer_ekyc_images',
    PERFORMER_REWARDS_MESSAGE_AT_LAST_MONEY_REQUEST_LOGS = 'performer_rewards_message_at_last_money_request_logs',
    ADJUST_EVENT_LOGS = 'adjust_event_logs',
    PERFORMER_GALLERY_PAYMENT_LOGS = 'performer_gallery_payment_logs',
    CAMPAIGN_PROGRESS_LOGS = 'campaign_progress_logs',
    POST_VIOLATION_REPORTS = 'post_violation_reports',
    PAYMENT_COMPANY_ALLOCATIONS = 'payment_company_allocations',
}

// PaymentCreatedByAccountTypeEnum and PaymentCreatedByAccountType are used to determine the type of user who created the payment
// PaymentCreatedByAccountTypeEnum only use for database
export enum PaymentCreatedByAccountTypeEnum {
    ADMINISTRATOR = 'administrator',
    USER = 'user',
}

// TokenAccountTypeEnum and TokenAccountTypeType are used to determine the type of user who created the token
// TokenAccountTypeEnum only use for database
export enum TokenAccountTypeEnum {
    USER = 'user',
    PERFORMER = 'performer',
    ADMINISTRATOR = 'administrator',
    TEMP_USER = 'temp_user',
}

// ContentApprovalTableNameEnum and ContentApprovalTableName are used to determine the table name of the content approval
// ContentApprovalTableNameEnum only use for database
export enum ContentApprovalTableNameEnum {
    USERS = 'users',
    PERFORMERS = 'performers',
    USER_GALLERY_GROUPS = 'user_gallery_groups',
    PERFORMER_GALLERY_GROUPS = 'performer_gallery_groups',
    POSTS = 'posts',
}

export enum TencentLiveStageLiveStreamModeEnum {
    FREE_LIVE = 'FreeLive',
    PREMIUM_LIVE = 'PremiumLive',
    PREMIUM_2SHOT = '2shortLive',
}
