enum ConfigKey {
    NODE_ENV = 'NODE_ENV',
    APP_PORT = 'APP_PORT',
    CORS_WHITELIST = 'CORS_WHITELIST',
    APP_PREFIX = 'APP_PREFIX',

    // Logging
    LOG_ENABLE_LOG_TO_FILE = 'LOG_ENABLE_LOG_TO_FILE',
    LOG_ROOT_FOLDER = 'LOG_ROOT_FOLDER',
    LOG_MAX_FILES = 'LOG_MAX_FILES',
    LOG_MAX_SIZE = 'LOG_MAX_SIZE',
    LOG_LEVEL = 'LOG_LEVEL',

    // Database
    POSTGRES_HOST = 'POSTGRES_HOST',
    POSTGRES_PORT = 'POSTGRES_PORT',
    POSTGRES_USERNAME = 'POSTGRES_USERNAME',
    POSTGRES_PASSWORD = 'POSTGRES_PASSWORD',
    POSTGRES_DATABASE = 'POSTGRES_DATABASE',

    // JWT - authentication
    JWT_ACCESS_TOKEN_SECRET = 'JWT_ACCESS_TOKEN_SECRET',
    JWT_ACCESS_TOKEN_EXPIRED_IN = 'JWT_ACCESS_TOKEN_EXPIRED_IN',
    JWT_REFRESH_TOKEN_SECRET = 'JWT_REFRESH_TOKEN_SECRET',
    JWT_REFRESH_TOKEN_EXPIRED_IN = 'JWT_REFRESH_TOKEN_EXPIRED_IN',

    // AWS
    AWS_REGION = 'AWS_REGION',
    AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID',
    AWS_SECRET_ACCESS_KEY = 'AWS_SECRET_ACCESS_KEY',
    AWS_S3_BUCKET = 'AWS_S3_BUCKET',
    AWS_S3_SIGNED_URL_EXPIRED_IN_SECOND = 'AWS_S3_SIGNED_URL_EXPIRED_IN_SECOND',

    CLOUD_FRONT_URL = 'CLOUD_FRONT_URL',
}

export default ConfigKey;
